package com.abc.greendaoexample.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MOVIE".
 */
public class Movie {

    private Long id;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String release_date;
    /** Not-null value. */
    private String description;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Movie() {
    }

    public Movie(Long id) {
        this.id = id;
    }

    public Movie(Long id, String title, String release_date, String description) {
        this.id = id;
        this.title = title;
        this.release_date = release_date;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getRelease_date() {
        return release_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
